import { expect, test } from '@playwright/test';

test('wide dock owns tasks while compact and mobile retain the original task surface', async ({ page }) => {
  test.setTimeout(150_000);
  page.setDefaultTimeout(10_000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/');
  await expect(page.locator('#app')).toHaveAttribute('data-readiness', 'enhanced', { timeout: 90_000 });
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'DEU'));
  await expect(page.locator('#countryProperties')).toBeVisible();
  await expect.poll(async () => {
    const panel = await page.locator('#rightPanel').boundingBox();
    return Math.round(panel.x + panel.width);
  }).toBe(1440);
  const panel = await page.locator('#rightPanel').boundingBox();
  const map = await page.locator('#map').boundingBox();
  expect(panel.y).toBe(52);
  // The wide editor overlays the map edge without resizing the map viewport,
  // so opening the editor must not shift the geographic projection.
  expect(Math.round(map.x + map.width)).toBe(1440);
  expect(Math.round(map.x + map.width)).toBeGreaterThan(Math.round(panel.x));
  await expect(page.locator('#leftPanel')).toBeVisible();
  await page.locator('#focusSelectedObjectBtn').click();
  await page.locator('#actionsTabBtn').click();
  await page.locator('#annexTerritoryBtn').click();
  await expect(page.locator('#editorTaskSlot #modeEditingContext')).toBeVisible();
  await expect(page.locator('#modeTaskName')).toHaveText('영토 편입');
  await expect(page.locator('#editorScrollBody')).not.toBeVisible();
  await expect(page.locator('#modeTaskMinimizeBtn')).not.toBeVisible();
  await expect(page.locator('#modePrimaryBtn')).toBeDisabled();
  await page.setViewportSize({ width: 1000, height: 900 });
  await expect(page.locator('#app')).toHaveAttribute('data-layout', 'compact');
  await expect(page.locator('#mapTopContextSlot #modeEditingContext')).toBeVisible();
  await expect(page.locator('#modeTaskMinimizeBtn')).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 900 });
  await expect(page.locator('#editorTaskSlot #modeEditingContext')).toBeVisible();
  await expect(page.locator('#modeTaskName')).toHaveText('영토 편입');
  await page.locator('#modeCancelBtn').click();
  await expect(page.locator('#rightPanel')).toHaveAttribute('data-editor-content', 'properties');
  await expect(page.locator('#actionsTabBtn')).toHaveAttribute('aria-selected', 'true');
  await page.locator('#mergeCountryBtn').click();
  await expect(page.locator('#editorTaskSlot #modeTaskName')).toHaveText('국가 합병');
  await page.locator('#zoomOutBtn').click();
  await page.locator('#zoomOutBtn').click();
  await page.locator('text.country-label').filter({ hasText: /^프랑스$/ }).click();
  await expect(page.locator('#modePrimaryBtn')).toBeEnabled();
  await page.locator('#modePrimaryBtn').click();
  await expect(page.locator('#geometryPreviewSummary')).toBeVisible({ timeout: 30_000 });
  await expect(page.locator('#modePrimaryBtn')).toBeEnabled({ timeout: 30_000 });
  await page.locator('#modePrimaryBtn').click();
  await expect(page.locator('#rightPanel')).toHaveAttribute('data-editor-content', 'properties', { timeout: 30_000 });
  await page.locator('#undoBtn').click();
  await page.locator('#layerSearchInput').fill('프랑스');
  await expect(page.locator('#layerSearchResults [data-item-id="FRA"]')).toHaveCount(1);
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'DEU'));
  await page.locator('#actionsTabBtn').click();
  await page.locator('#mergeCountryBtn').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('#app')).toHaveAttribute('data-layout', 'mobile');
  await expect(page.locator('#mapTopContextSlot #modeEditingContext')).toBeVisible();
  await expect(page.locator('#editorTaskSlot')).not.toBeVisible();
  await page.locator('#modeCancelBtn').click();
  expect(errors).toEqual([]);
});
