import { expect, test } from '@playwright/test';

test('layer footer owns actions and header owns history across desktop and mobile', async ({ page }) => {
  test.setTimeout(150_000);
  page.setDefaultTimeout(10_000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/?debug=1');
  await expect(page.locator('#app')).toHaveAttribute('data-readiness', 'enhanced', { timeout: 90_000 });
  await expect(page.locator('#mobileCreateBtn,#mapCommandToolbar,#objectLockMenuBtn,#objectDeleteMenuBtn,#multiPropertiesLockInput,#editorCommonActions,#editorDeleteActions')).toHaveCount(0);
  await expect(page.locator('.topbar #undoBtn')).toHaveCount(1);
  await expect(page.locator('.topbar #mobileFileBtn')).toHaveCount(1);
  await expect(page.locator('.layer-panel-footer #createMenuBtn')).toBeVisible();
  await expect(page.locator('#objectLockBtn')).toBeDisabled();
  await expect(page.locator('#objectDeleteBtn')).toBeDisabled();
  const footerY = (await page.locator('.layer-panel-footer').boundingBox()).y;
  await page.locator('.layer-list').evaluate(el => { el.scrollTop = el.scrollHeight; });
  expect((await page.locator('.layer-panel-footer').boundingBox()).y).toBe(footerY);
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'DEU'));
  await expect(page.locator('#countryProperties')).toBeVisible();
  await page.locator('#objectLockBtn').click();
  await expect(page.locator('#objectLockBtn')).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('#objectDeleteBtn')).toBeDisabled();
  await page.locator('#layerSearchInput').fill('프랑스');
  await page.locator('#layerSearchResults [data-item-id="FRA"]').click({ modifiers: ['Control'] });
  await expect(page.locator('#multiSelectionCount')).toHaveText('2개 선택됨');
  await expect(page.locator('#objectLockBtn')).toHaveAttribute('aria-label', '모두 잠금');
  await page.locator('#objectLockBtn').click();
  await expect(page.locator('#objectLockBtn')).toHaveAttribute('aria-pressed', 'true');
  await page.locator('#undoBtn').click();
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'DEU'));
  await expect(page.locator('#objectLockBtn')).toHaveAttribute('aria-pressed', 'true');
  await page.locator('#objectLockBtn').click();
  await page.locator('#objectDeleteBtn').click();
  await expect(page.locator('#confirmModal')).toBeVisible();
  await page.locator('#confirmModalOkBtn').click();
  await expect(page.locator('#objectDeleteBtn')).toBeDisabled();
  await page.locator('#undoBtn').click();
  await page.locator('#layerSearchInput').fill('독일');
  await expect(page.locator('#layerSearchResults [data-item-id="DEU"]')).toHaveCount(1);
  await page.locator('#createMenuBtn').click();
  await expect(page.locator('#createMenu')).toBeVisible();
  const menu = await page.locator('#createMenu').boundingBox();
  const trigger = await page.locator('#createMenuBtn').boundingBox();
  expect(menu.y).toBeGreaterThanOrEqual(0);
  expect(menu.y + menu.height).toBeLessThanOrEqual(trigger.y);
  await page.locator('#mobileCloseCreateBtn').click();
  await page.locator('#mobileFileBtn').click();
  await expect(page.locator('#fileMenu')).toBeVisible();
  expect((await page.locator('#fileMenu').boundingBox()).x).toBeLessThan(300);
  await page.locator('#mobileFileBtn').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('#app')).toHaveAttribute('data-layout', 'mobile');
  if (await page.locator('#mobileMapBtn').getAttribute('aria-expanded') !== 'true') await page.locator('#mobileMapBtn').click();
  await expect(page.locator('#createMenuBtn')).toBeVisible();
  await expect.poll(async () => {
    const footer = await page.locator('.layer-panel-footer').boundingBox();
    return footer.y + footer.height;
  }).toBeLessThanOrEqual(780);
  await page.locator('#createMenuBtn').click();
  await expect(page.locator('#createMenu')).toBeVisible();
  const mobileMenu = await page.locator('#createMenu').boundingBox();
  expect(mobileMenu.x).toBeGreaterThanOrEqual(0);
  expect(mobileMenu.x + mobileMenu.width).toBeLessThanOrEqual(390);
  expect(mobileMenu.y).toBeGreaterThan(52);
  await page.keyboard.press('Escape');
  await expect(page.locator('#createMenu')).not.toBeVisible();
  await expect(page.locator('.map-view-toolbar')).toHaveCount(1);
  expect(errors).toEqual([]);
});
