import { test, expect } from '@playwright/test';
import { builtinSubunitId } from '../../assets/js/modules/builtin-subunits.js';

test('country selection reveals the same layer through collapsed folders, virtualization and search', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/');
  await expect(page.locator('#app')).toHaveAttribute('data-readiness', 'enhanced', { timeout: 90_000 });
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'POL'));
  const poland = page.locator('.layer-list [data-layer-group="countries"][data-item-id="POL"]');
  await expect(poland).toHaveClass(/is-selected/);
  await expect(poland).toBeInViewport();
  await page.locator('.layer-list').evaluate(el => { el.scrollTop = 0; });
  await expect.poll(() => page.locator('.layer-list').evaluate(el => el.scrollTop)).toBe(0);
  await page.locator('#layerSearchInput').fill('일치하지않는검색어');
  await expect(page.locator('#layerSearchResults .layer-empty')).toBeVisible();
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'DEU'));
  await expect(page.locator('#layerSearchInput')).toHaveValue('');
  await expect(page.locator('.layer-list .layer-child[data-item-id="DEU"]')).toHaveClass(/is-selected/);
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'DNK'));
  const denmark = page.locator('.layer-list .layer-child[data-item-id="DNK"]');
  const greenlandId = builtinSubunitId('GRL');
  const greenland = page.locator(`.layer-list .layer-child[data-layer-group="subunits"][data-item-id="${greenlandId}"]`);
  await expect(denmark.locator('[data-layer-parent-toggle]')).toHaveAttribute('aria-expanded', 'false');
  await expect(greenland).toHaveCount(0);
  await page.evaluate(id => window.PANDOLAB_TERRITORIAL.select('subunit', id), greenlandId);
  await expect(greenland).toHaveClass(/is-selected/);
  await expect(greenland).toBeInViewport();
  await expect(denmark.locator('[data-layer-parent-toggle]')).toHaveAttribute('aria-expanded', 'true');
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'DNK'));
  await expect(greenland).toBeVisible();
  await denmark.locator('[data-layer-parent-toggle]').click();
  await expect(greenland).toHaveCount(0);
  await page.locator('#layerSearchInput').fill('그린란드');
  await expect(page.locator(`#layerSearchResults .layer-child[data-item-id="${greenlandId}"]`)).toBeVisible();
  await page.locator('#layerSearchInput').fill('');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('#app')).toHaveAttribute('data-layout', 'mobile');
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'POL'));
  if (await page.locator('#mobileMapBtn').getAttribute('aria-expanded') !== 'true') await page.locator('#mobileMapBtn').click();
  await expect(poland).toHaveClass(/is-selected/);
  await expect(poland).toBeInViewport();
  await page.evaluate(id => window.PANDOLAB_TERRITORIAL.select('subunit', id), greenlandId);
  if (await page.locator('#mobileMapBtn').getAttribute('aria-expanded') !== 'true') await page.locator('#mobileMapBtn').click();
  await expect(greenland).toHaveClass(/is-selected/);
  await expect(greenland).toBeInViewport();
  expect(errors).toEqual([]);
});
