import { test, expect } from '@playwright/test';

test('one responsive view control and theme-only preferences preserve editing and saved styles', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const preferences = { version: 2, appearance: { theme: 'light' }, labels: { country: { font: 'serif', color: '#123456' }, place: { font: 'gothic', color: '#654321', pointColor: '#abcdef' } }, selection: { color: '#ff0000', outlineVisible: false, fillStrength: 0.8 } };
  await page.addInitScript(value => localStorage.setItem('pandolab-user-preferences', JSON.stringify(value)), preferences);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/?debug=1');
  await expect(page.locator('#app')).toHaveAttribute('data-readiness', 'enhanced', { timeout: 90_000 });
  await expect(page.locator('#mapToolToolbar,#engineStatus,#shortcutHelpModal,#keyboardHelpBtn,#objectCoastReconcileMenuBtn')).toHaveCount(0);
  await expect(page.locator('.map-view-toolbar')).toHaveCount(1);
  await expect(page.locator('#zoomInBtn')).toBeVisible();
  await expect(page.locator('[data-layer-group="genericFeatures"].layer-folder')).toBeHidden();
  await page.locator('#mobileFileBtn').click();
  await page.locator('#preferencesBtn').click();
  await expect(page.locator('#preferencesModal')).toBeVisible();
  await expect(page.locator('#preferencesModal input[type="color"]')).toHaveCount(1);
  await expect(page.locator('#preferencesModal input[type="range"]')).toHaveCount(0);
  await page.locator('#preferencesThemeInput').selectOption('dark', { force: true });
  await page.locator('#preferencesResetBtn').click();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('pandolab-user-preferences')).appearance.theme)).toBe('light');
  await page.locator('#preferencesCancelBtn').click();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('pandolab-user-preferences')))).toEqual(preferences);
  const interaction = await page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle.selection);
  expect(interaction.outlineVisible).toBe(true);
  expect(interaction.fillStrength).toBe(0.35);
  expect(interaction.color).not.toBe('#ff0000');
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('country', 'DEU'));
  await expect(page.locator('#countryProperties')).toBeVisible();
  await expect(page.locator('#editBorderBtn')).toHaveCount(1);
  await page.locator('#mobileFileBtn').click();
  await page.locator('#preferencesBtn').click();
  const rulesBefore = await page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle);
  await page.locator('[data-preference-accent="#8b5cf6"]').click();
  await expect.poll(() => page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle.selection.color)).toBe('#8b5cf6');
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('pandolab-user-preferences')).appearance.accentColor)).toBeUndefined();
  const rulesAfter = await page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle);
  expect(rulesAfter.selection.primary).toEqual(rulesBefore.selection.primary);
  expect(rulesAfter.selection.secondary).toEqual(rulesBefore.selection.secondary);
  expect(rulesAfter.drawOrder).toEqual(rulesBefore.drawOrder);
  await page.locator('#preferencesApplyBtn').click();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('pandolab-user-preferences')).appearance.accentColor)).toBe('#8b5cf6');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('#app')).toHaveAttribute('data-layout', 'mobile');
  if (await page.locator('#mobileCloseRightBtn').isVisible()) await page.locator('#mobileCloseRightBtn').click();
  await expect(page.locator('.map-view-toolbar')).toHaveCount(1);
  await expect(page.locator('#zoomInBtn')).toBeVisible();
  const control = await page.locator('#zoomInBtn').boundingBox();
  expect(control.x).toBeGreaterThanOrEqual(0); expect(control.x + control.width).toBeLessThanOrEqual(391);
  const before = await page.evaluate(() => window.__PANDOLAB_VIEW_DEBUG__.snapshot());
  await page.locator('#zoomInBtn').click();
  await expect.poll(() => page.evaluate(() => window.__PANDOLAB_VIEW_DEBUG__.snapshot())).not.toEqual(before);
  await page.locator('#resetViewBtn').click();
  await page.locator('#mobileFileBtn').click();
  await page.locator('#preferencesBtn').click();
  await page.locator('#preferencesAccentInput').evaluate(input => { input.value = '#e87924'; input.dispatchEvent(new input.ownerDocument.defaultView.Event('input', { bubbles: true })); });
  await expect.poll(() => page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle.selection.color)).toBe('#e87924');
  await page.locator('#preferencesCancelBtn').click();
  await expect.poll(() => page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle.selection.color)).toBe('#8b5cf6');
  expect(errors).toEqual([]);
});
